"""
This type stub file was generated by pyright.
"""

from autobahn.twisted.websocket import WebSocketClientFactory
from twisted.internet.protocol import ReconnectingClientFactory

class BinanceReconnectingClientFactory(ReconnectingClientFactory):
    initialDelay = ...
    maxDelay = ...
    maxRetries = ...


class BinanceClientFactory(WebSocketClientFactory, BinanceReconnectingClientFactory):
    def __init__(self, *args, payload=..., **kwargs) -> None:
        ...
    
    _reconnect_error_payload = ...
    def startedConnecting(self, connector): # -> None:
        ...
    
    def clientConnectionFailed(self, connector, reason): # -> None:
        ...
    
    def clientConnectionLost(self, connector, reason): # -> None:
        ...
    
    def buildProtocol(self, addr): # -> BinanceClientProtocol:
        ...
    


