"""
This type stub file was generated by pyright.
"""

from autobahn.twisted.websocket import WebSocketClientProtocol

class BinanceClientProtocol(WebSocketClientProtocol):
    def __init__(self, factory, payload=...) -> None:
        ...
    
    def onOpen(self): # -> None:
        ...
    
    def onConnect(self, response): # -> None:
        ...
    
    def onMessage(self, payload, isBinary): # -> None:
        ...
    
    def onClose(self, wasClean, code, reason): # -> None:
        ...
    
    def onPing(self, payload): # -> None:
        ...
    
    def onPong(self, payload): # -> None:
        ...
    


