"""
This type stub file was generated by pyright.
"""

from binance.websocket.binance_socket_manager import BinanceSocketManager

class BinanceWebsocketClient(BinanceSocketManager):
    def __init__(self, stream_url) -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def live_subscribe(self, stream, id, callback, **kwargs): # -> Literal[False] | None:
        """live subscribe websocket
        Connect to the server
        - UM Futures: wss://fstream.binance.com/ws
        - UM Futures testnet: wss://stream.binancefuture.com/ws
        - CM Futures: wss://dstream.binance.com/ws
        - CM Futures testnet: wss://dstream.binancefuture.com/ws

        and sending the subscribe message, e.g.

        {"method": "SUBSCRIBE","params":["btcusdt@miniTicker"],"id": 100}

        """
        ...
    
    def instant_subscribe(self, stream, callback, **kwargs): # -> Literal[False] | None:
        """Instant subscribe, e.g.
        wss://fstream.binance.com/ws/btcusdt@bookTicker
        wss://fstream.binance.com/stream?streams=btcusdt@bookTicker/bnbusdt@bookTicker

        """
        ...
    


