"""
This type stub file was generated by pyright.
"""

def pm_exchange_info(self, symbol: str = ...):
    """
    |
    | **Portfolio Margin Exchange Information**
    | *Current Portfolio Margin exchange trading rules.*

    :API endpoint: ``GET /fapi/v1/pmExchangeInfo``
    :API doc: https://binance-docs.github.io/apidocs/futures/en/#portfolio-margin-endpoints

    :parameter symbol: string; the trading pair.
    |
    """
    ...

